export enum MutationTypes {
  SET_COUNTER = "SET_COUNTER",
  RESET_COUNTER = "RESET_COUNTER",
  SET_EMPLOYEE_DATA = "SET_EMPLOYEE_DATA",
  SELECT_EMPLOYEE = "SELECT_EMPLOYEE",
  SET_MESSAGE = "SET_MESSAGE",
}
