export enum ActionTypes {
  GET_COUTNER = "GET_COUTNER",
  SET_ROOT_DISPATCH = "SET_ROOT_DISPATCH",
  FETCH_EMPLOYEES = "FETCH_EMPLOYEES",
  SET_EMPLOYEE_DATA = "SET_EMPLOYEE_DATA",
  SELECT_EMPLOYEE = "SELECT_EMPLOYEE"
}
